package CW2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.


 */
/**
 *
 * @author hjabbar1
 */
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class Secretary extends javax.swing.JFrame {
//ArrayList of type Student is declared named sArrayList

    ArrayList<Student> sArrayList = new ArrayList<Student>();
    ArrayList<Tutor> tArrayList = new ArrayList<Tutor>();

    JFileChooser fc; // File chooser
    File dir;
    File file = null;
    DefaultTableModel sModel, tModel;

    /* Creates new form Secretary */
    public Secretary() {
        initComponents();

        sModel = new DefaultTableModel();
        jTableStudent.setModel(sModel);
        sModel.addColumn("UoB Number");
        sModel.addColumn("Firstname");
        sModel.addColumn("Surname");
        sModel.addColumn("Email");
        sModel.addColumn("Course");
        sModel.addColumn("Course Type");
        sModel.addColumn("Course Duration");
        sModel.addColumn("Start Date");
        sModel.addColumn("End Date");

        tModel = new DefaultTableModel();
        jTableTutor.setModel(tModel);
        tModel.addColumn("ID");
        tModel.addColumn("Title");
        tModel.addColumn("Firstname");
        tModel.addColumn("Surname");
        tModel.addColumn("Email");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblMessageStudent1 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        jpStudent = new javax.swing.JPanel();
        lbluobnumber = new javax.swing.JLabel();
        txtUobNumber = new javax.swing.JTextField();
        txtSFirstname = new javax.swing.JTextField();
        lblFirstname = new javax.swing.JLabel();
        txtSSurname = new javax.swing.JTextField();
        lblSurname = new javax.swing.JLabel();
        txtSEmail = new javax.swing.JTextField();
        lbluobnumber3 = new javax.swing.JLabel();
        txtCourse = new javax.swing.JTextField();
        lblCourse = new javax.swing.JLabel();
        txtCourseType = new javax.swing.JTextField();
        lblCourseType = new javax.swing.JLabel();
        txtCourseDuration = new javax.swing.JTextField();
        lbCourseDuration = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        lblStartDate = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        lblEndDate = new javax.swing.JLabel();
        btnUpdateStudent = new javax.swing.JButton();
        btnRemoveStudent = new javax.swing.JButton();
        btnClearStudent = new javax.swing.JButton();
        jPanelResults = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTutor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblTitletut = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtTFirstname = new javax.swing.JTextField();
        lblFirstnametut = new javax.swing.JLabel();
        txtTSurname = new javax.swing.JTextField();
        lblSurnametut = new javax.swing.JLabel();
        txtTEmail = new javax.swing.JTextField();
        lblEmailTut = new javax.swing.JLabel();
        btnUpdateTutor = new javax.swing.JButton();
        btnRemoveTutor = new javax.swing.JButton();
        btnClearTutor = new javax.swing.JButton();
        jPanelButtons = new javax.swing.JPanel();
        btnDisplay = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Student Information");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1710, 1000));

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Tutor Allocation");

        jpStudent.setBorder(javax.swing.BorderFactory.createTitledBorder("Student Information"));

        lbluobnumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbluobnumber.setText("UoB Number: ");

        lblFirstname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFirstname.setText("Firstname: ");

        lblSurname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSurname.setText("Surname: ");

        lbluobnumber3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbluobnumber3.setText("Email: ");

        lblCourse.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCourse.setText("Course: ");

        lblCourseType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCourseType.setText("Course Type (Postgrad/Undergrad): ");

        lbCourseDuration.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCourseDuration.setText("Course Duration: ");

        lblStartDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStartDate.setText("Start Year: ");

        lblEndDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEndDate.setText("End Year: ");

        btnUpdateStudent.setText("Update");
        btnUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStudentActionPerformed(evt);
            }
        });

        btnRemoveStudent.setText("Remove");
        btnRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStudentActionPerformed(evt);
            }
        });

        btnClearStudent.setText("Clear");
        btnClearStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpStudentLayout = new javax.swing.GroupLayout(jpStudent);
        jpStudent.setLayout(jpStudentLayout);
        jpStudentLayout.setHorizontalGroup(
            jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStudentLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpStudentLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbluobnumber3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCourse)
                            .addComponent(lblFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbluobnumber)))
                    .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCourseType)
                        .addComponent(lblEndDate)
                        .addComponent(lbCourseDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblStartDate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpStudentLayout.createSequentialGroup()
                        .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCourseDuration, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourseType, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourse, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSSurname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSFirstname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUobNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemoveStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClearStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jpStudentLayout.setVerticalGroup(
            jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluobnumber)
                    .addComponent(txtUobNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateStudent))
                .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpStudentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstname)
                            .addComponent(txtSFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSurname)
                            .addComponent(txtSSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpStudentLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnRemoveStudent)))
                .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpStudentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbluobnumber3)
                            .addComponent(txtSEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourse)
                            .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpStudentLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnClearStudent)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseType)
                    .addComponent(txtCourseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCourseDuration)
                    .addComponent(txtCourseDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartDate)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndDate)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelResults.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));

        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UoB Number", "Firstname", "Surname", "Email", "Course", "Course Type", "Duration", "Start Date", "End Date"
            }
        ));
        jScrollPane1.setViewportView(jTableStudent);

        jTableTutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Firstname", "Surname", "Email"
            }
        ));
        jScrollPane2.setViewportView(jTableTutor);

        javax.swing.GroupLayout jPanelResultsLayout = new javax.swing.GroupLayout(jPanelResults);
        jPanelResults.setLayout(jPanelResultsLayout);
        jPanelResultsLayout.setHorizontalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanelResultsLayout.setVerticalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tutor Information"));

        txtID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        lblID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblID.setText("ID: ");

        lblTitletut.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitletut.setText("Title(Mr, Mrs, Miss, Dr, Professor): ");

        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });

        txtTFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTFirstnameActionPerformed(evt);
            }
        });

        lblFirstnametut.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFirstnametut.setText("Firstname: ");

        txtTSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTSurnameActionPerformed(evt);
            }
        });

        lblSurnametut.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSurnametut.setText("Surname: ");

        txtTEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTEmailActionPerformed(evt);
            }
        });

        lblEmailTut.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmailTut.setText("Email: ");

        btnUpdateTutor.setText("Update");
        btnUpdateTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTutorActionPerformed(evt);
            }
        });

        btnRemoveTutor.setText("Remove");
        btnRemoveTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTutorActionPerformed(evt);
            }
        });

        btnClearTutor.setText("Clear");
        btnClearTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitletut)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstnametut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSurnametut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailTut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID)
                    .addComponent(txtTitle)
                    .addComponent(txtTFirstname)
                    .addComponent(txtTSurname)
                    .addComponent(txtTEmail))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnUpdateTutor)
                .addGap(43, 43, 43)
                .addComponent(btnRemoveTutor)
                .addGap(44, 44, 44)
                .addComponent(btnClearTutor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitletut)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstnametut)
                    .addComponent(txtTFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurnametut)
                    .addComponent(txtTSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailTut)
                    .addComponent(txtTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateTutor)
                    .addComponent(btnRemoveTutor)
                    .addComponent(btnClearTutor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnClearAll.setText("Clear All");
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnDisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnClearAll)
                .addGap(52, 52, 52)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplay)
                    .addComponent(btnClearAll)
                    .addComponent(Exit)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 0, 0));
        lblMessage.setText("Only 4 - 8 students can be assigned to a tutor group");
        lblMessage.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(67, 67, 67))
                            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanelResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanelResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showStudentData() {
        String matrix[][] = new String[sArrayList.size()][9];
        for (int i = 0; i < sArrayList.size(); i++) {
            matrix[i][0] = sArrayList.get(i).getUobnumber();
            matrix[i][1] = sArrayList.get(i).getFirstname();
            matrix[i][2] = sArrayList.get(i).getSurname();
            matrix[i][3] = sArrayList.get(i).getEmail();
            matrix[i][4] = sArrayList.get(i).getCourse();
            matrix[i][5] = sArrayList.get(i).getCourseType();
            matrix[i][6] = sArrayList.get(i).getCourseDuration();
            matrix[i][7] = sArrayList.get(i).getStartDate();
            matrix[i][8] = sArrayList.get(i).getEndDate();
        }
        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
                matrix, new String[]{
                    "Uob Number", "Firstname", "Surname", "Email", "Course",
                    "Course Type", "Duration", "Start Date", "End Date"
                }));
    }

    public void showTutorData() {
        String matrix[][] = new String[tArrayList.size()][5];
        for (int i = 0; i < tArrayList.size(); i++) {
            matrix[i][0] = tArrayList.get(i).getId();
            matrix[i][1] = tArrayList.get(i).getTitle();
            matrix[i][2] = tArrayList.get(i).getFirstname();
            matrix[i][3] = tArrayList.get(i).getSurname();
            matrix[i][4] = tArrayList.get(i).getEmail();
        }
        jTableTutor.setModel(new javax.swing.table.DefaultTableModel(
                matrix, new String[]{"ID", "Title", "Firstname", "Surname", "Email"}));
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        getRecord(); //gets all the records from all the fields filled in
        fc = new JFileChooser(dir); // create a new filechooser

        // Student table model
        DefaultTableModel sModel = (DefaultTableModel) jTableStudent.getModel();

        // Tutor table model
        DefaultTableModel tModel = (DefaultTableModel) jTableTutor.getModel();

        FileNameExtensionFilter filter;
        filter = new FileNameExtensionFilter("*.txt", new String[]{"txt"});
        fc.addChoosableFileFilter(filter); // when saving the data, an option for saving a file is shown
        int option = fc.showSaveDialog(this); //shows a dialog box
        if (option == JFileChooser.APPROVE_OPTION) { // if the user clicks the OK button on the dialog box
            dir = fc.getCurrentDirectory(); // File object is equal to the filechooser

            // This is adding rows to the student table
            sModel.addRow(new Object[]{txtUobNumber.getText(), txtSFirstname.getText(),
                txtSSurname.getText(), txtSEmail.getText(), txtCourse.getText(), txtCourseType.getText(),
                txtCourseDuration.getText(), txtStartDate.getText(), txtEndDate.getText()});
            
                // This is adding rows to the tutor table
                tModel.addRow(new Object[]{txtID.getText(), txtTitle.getText(), txtTFirstname.getText(),
                    txtTSurname.getText(), txtTEmail.getText()});
                file = fc.getSelectedFile(); // can choose a file
            
            try {
                write(); // writes the information from the tables to a file in a certain format
                lblMessage.setText("File saved successfully");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtTFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTFirstnameActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void txtTEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTEmailActionPerformed

    private void txtTSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTSurnameActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        FileInputStream fis = null; // File input stream equals nothing
        fc = new JFileChooser(dir); //create a new file chooser with a file variable
        int option = fc.showOpenDialog(this); // open a dialog
        if (option == JFileChooser.APPROVE_OPTION) { // show dialog with the ok option
            file = fc.getSelectedFile(); //get the file 
            dir = fc.getCurrentDirectory(); //goes to the current directory
            try {
                String str = ""; //empty string
                fis = new FileInputStream(file); //create a new file input stream writing to file
                int len = (int) file.length(); // int variable equal to the length of file 
                for (int i = 0; i < len; i++) {
                    char str2 = 0;
                    try {
                        str2 = (char) fis.read();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    str = str + str2;
                }
                lblMessage.setText(str); // Text area shows the result formatted
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    if (fis != null) { //if file input stream is empty
                        fis.close(); // close the stream
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        // Empty all student fields
        txtUobNumber.setText("");
        txtSFirstname.setText("");
        txtSSurname.setText("");
        txtSEmail.setText("");
        txtCourse.setText("");
        txtCourseType.setText("");
        txtCourseDuration.setText("");
        txtStartDate.setText("");
        txtEndDate.setText("");

        //Empty all tutor fields
        txtID.setText("");
        txtTitle.setText("");
        txtTFirstname.setText("");
        txtTSurname.setText("");
        txtTEmail.setText("");

        if (jTableStudent.getRowCount() > 0) {
            for (int i = jTableStudent.getRowCount() - 1; i > -1; i--) {
                sModel.removeRow(i);
                lblMessage.setText("");
            }
        }
        if (jTableTutor.getRowCount() > 0) {
            for (int i = jTableTutor.getRowCount() - 1; i > -1; i--) {
                tModel.removeRow(i);
            }
            lblMessage.setText("");
        }

    }//GEN-LAST:event_btnClearAllActionPerformed


    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void btnUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStudentActionPerformed
        DefaultTableModel sModel = (DefaultTableModel) jTableStudent.getModel();
        sModel.setValueAt(txtUobNumber.getText(), jTableStudent.getSelectedRow(), 0);
        sModel.setValueAt(txtSFirstname.getText(), jTableStudent.getSelectedRow(), 1);
        sModel.setValueAt(txtSSurname.getText(), jTableStudent.getSelectedRow(), 2);
        sModel.setValueAt(txtSEmail.getText(), jTableStudent.getSelectedRow(), 3);
        sModel.setValueAt(txtCourse.getText(), jTableStudent.getSelectedRow(), 4);
        sModel.setValueAt(txtCourseType.getText(), jTableStudent.getSelectedRow(), 5);
        sModel.setValueAt(txtCourseDuration.getText(), jTableStudent.getSelectedRow(), 6);
        sModel.setValueAt(txtStartDate.getText(), jTableStudent.getSelectedRow(), 7);
        sModel.setValueAt(txtEndDate.getText(), jTableStudent.getSelectedRow(), 8);

        lblMessage.setText("Updated student(s) successfully");
    }//GEN-LAST:event_btnUpdateStudentActionPerformed

    private void btnUpdateTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTutorActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTableTutor.getModel();
        tModel.setValueAt(txtID.getText(), jTableTutor.getSelectedRow(), 0);
        tModel.setValueAt(txtTitle.getText(), jTableTutor.getSelectedRow(), 1);
        tModel.setValueAt(txtTFirstname.getText(), jTableTutor.getSelectedRow(), 2);
        tModel.setValueAt(txtTSurname.getText(), jTableTutor.getSelectedRow(), 3);
        tModel.setValueAt(txtTEmail.getText(), jTableTutor.getSelectedRow(), 4);
        lblMessage.setText("Updated tutor(s) successfully");
    }//GEN-LAST:event_btnUpdateTutorActionPerformed

    private void btnRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStudentActionPerformed
        DefaultTableModel sModel = (DefaultTableModel) jTableStudent.getModel(); // creates a new student table model 
        sModel.removeRow(jTableStudent.getSelectedRow()); // removes row from the student table
        lblMessage.setText("Removed Student(s) from tutor group"); // shows a message
    }//GEN-LAST:event_btnRemoveStudentActionPerformed

    private void btnRemoveTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTutorActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTableTutor.getModel();
        tModel.removeRow(jTableTutor.getSelectedRow()); // Removes row from tutor table
        lblMessage.setText("Tutor(s) removed successfully");
    }//GEN-LAST:event_btnRemoveTutorActionPerformed

    private void btnClearStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearStudentActionPerformed
        txtUobNumber.setText("");
        txtSFirstname.setText("");
        txtSSurname.setText("");
        txtSEmail.setText("");
        txtCourse.setText("");
        txtCourseType.setText("");
        txtCourseDuration.setText("");
        txtStartDate.setText("");
        txtEndDate.setText("");
    }//GEN-LAST:event_btnClearStudentActionPerformed

    private void btnClearTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTutorActionPerformed
        txtID.setText("");
        txtTitle.setText("");
        txtTFirstname.setText("");
        txtTSurname.setText("");
        txtTEmail.setText("");
    }//GEN-LAST:event_btnClearTutorActionPerformed

    private void getRecord() {
        // Student Fields
        txtUobNumber.getText().toString();
        txtSFirstname.getText().toString();
        txtSSurname.getText().toString();
        txtSEmail.getText().toString();
        txtCourse.getText().toString();
        txtCourseType.getText().toString();
        txtCourseDuration.getText().toString();
        txtStartDate.getText().toString();
        txtEndDate.getText().toString();

        //Tutor Fields
        txtID.getText().toString();
        txtTitle.getText().toString();
        txtTFirstname.getText().toString();
        txtTSurname.getText().toString();
        txtTEmail.getText().toString();
    }

    private void write() throws IOException {
        BufferedWriter bw = null; //empty buffered writer

        // Student
        String uobnumber = txtUobNumber.getText().toString();
        String sFirstname = txtSFirstname.getText().toString();
        String sSurname = txtSSurname.getText().toString();

        // Tutor
        String id = txtID.getText().toString();
        String title = txtTitle.getText().toString();
        String tFirstname = txtTFirstname.getText().toString();
        String tSurname = txtTSurname.getText().toString();
        try {
            // a character output stream with a file output stream that gets the extention
            bw = new BufferedWriter(new FileWriter(file + getExtention(), true));
            //writes the data given in the format given

            bw.write("Student " + uobnumber + " is added to " + title + " " + tFirstname + " " + tSurname + "'s tutor group. " + "\n");

            // Shows this message when the data is written
            JOptionPane.showMessageDialog(rootPane, "Data Saved to file");

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (bw != null) { //if the buffered writer not empty
                bw.close(); //close the buffered writer
            }
        }
    }

    private String getExtention() {
        String ext = "";
        //the file choose gets the selected file and the decription of the file
        String extension = fc.getFileFilter().getDescription();
        if (extension.equals("*.txt")) {
            ext = ".txt";
        }
        return ext;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secretary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secretary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secretary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secretary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Secretary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnClearStudent;
    private javax.swing.JButton btnClearTutor;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnRemoveStudent;
    private javax.swing.JButton btnRemoveTutor;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateStudent;
    private javax.swing.JButton btnUpdateTutor;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelResults;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableStudent;
    private javax.swing.JTable jTableTutor;
    private javax.swing.JPanel jpStudent;
    private javax.swing.JLabel lbCourseDuration;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblCourseType;
    private javax.swing.JLabel lblEmailTut;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblFirstnametut;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMessageStudent1;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblSurnametut;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitletut;
    private javax.swing.JLabel lbluobnumber;
    private javax.swing.JLabel lbluobnumber3;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtCourseDuration;
    private javax.swing.JTextField txtCourseType;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSEmail;
    private javax.swing.JTextField txtSFirstname;
    private javax.swing.JTextField txtSSurname;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTEmail;
    private javax.swing.JTextField txtTFirstname;
    private javax.swing.JTextField txtTSurname;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtUobNumber;
    // End of variables declaration//GEN-END:variables

}
